#!/bin/bash

echo ' '
echo 'RUNNING VESIcal TESTING ROUTINES'
echo '================================'
echo ' '

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
cd $SCRIPT_DIR

python -m flake8
echo "flake8 completed"
echo " "

echo "Running unittest"
python -m unittest